import { useMemo, useState } from 'react';
import { BarChart3, Check, DollarSign, Download, Gauge, LockKeyhole, Settings2, ShieldCheck, Users, X } from 'lucide-react';

const feePresets = [2.5, 5, 7.5];

function AdminStat({ label, value, detail, tone = 'gold' }: { label: string; value: string; detail: string; tone?: 'gold' | 'green' | 'red' }) {
  const colors = tone === 'green' ? 'text-[#67d895]' : tone === 'red' ? 'text-[#e49787]' : 'text-[#f0d37c]';
  return <div className="panel-soft rounded-2xl p-5"><div className="mb-4 flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-[#819a8d]"><Gauge size={14} className={colors} /> {label}</div><div className={`font-display text-3xl font-bold ${colors}`}>{value}</div><div className="mt-2 text-[11px] text-[#789385]">{detail}</div></div>;
}

export default function AdminPage() {
  const [fee, setFee] = useState(5);
  const [maintenance, setMaintenance] = useState(false);
  const [saved, setSaved] = useState(false);
  const net = useMemo(() => Math.round(48750 * fee / 100), [fee]);
  return <div className="reveal">
    <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mb-2 flex items-center gap-2 font-mono-custom text-[10px] uppercase tracking-[.22em] text-[#d6a944]"><LockKeyhole size={13} /> Owner console · preview</div><h1 className="font-display text-3xl font-bold tracking-tight text-[#f0e7cf] sm:text-4xl">The house ledger.</h1><p className="mt-2 max-w-xl text-sm text-[#819a8d]">Operational visibility for fees, payouts, tables, and fair-play controls. Connect admin auth and a server ledger before using this with live money.</p></div><button onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2500); }} className="btn-primary flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold"><Check size={16} /> {saved ? 'Controls saved' : 'Save controls'}</button></div>
    <div className="mb-5 flex items-center gap-2 rounded-xl border border-[#d6a944]/30 bg-[#3b321e] px-4 py-3 text-xs leading-relaxed text-[#d9c37c]"><ShieldCheck size={16} className="shrink-0" /> Preview data is clearly labelled. No dashboard number here authorizes or settles a real payout.</div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><AdminStat label="Gross entry volume" value="KSh 48,750" detail="This period · simulated ledger" /><AdminStat label="Platform fees" value={`KSh ${net.toLocaleString('en-KE')}`} detail={`${fee}% transparent house fee`} tone="green" /><AdminStat label="Player payouts" value="KSh 46,312" detail="95% return target" /><AdminStat label="Active tables" value="128" detail="42 cash · 86 free" /></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <section className="panel rounded-2xl p-6"><div className="mb-5 flex items-center gap-2"><BarChart3 size={18} className="text-[#d6a944]" /><h2 className="font-display text-xl font-bold">Fairness & profit controls</h2></div><div className="space-y-5"><div><div className="mb-3 flex items-center justify-between text-sm font-semibold"><span>Platform fee on entry pool</span><span className="font-mono-custom text-[#f0d37c]">{fee}%</span></div><div className="grid grid-cols-3 gap-2">{feePresets.map((value) => <button key={value} onClick={() => setFee(value)} className={`rounded-xl border py-3 text-xs font-bold ${fee === value ? 'border-[#d6a944] bg-[#3b321e] text-[#f0d37c]' : 'border-[#345346] bg-[#142e25] text-[#9ab0a1]'}`}>{value}%</button>)}</div><p className="mt-2 text-[11px] leading-relaxed text-[#789385]">Shown before a player joins. Prize calculation: entry pool minus this fee. No hidden spread.</p></div><div className="flex items-center justify-between rounded-xl border border-[#345346] bg-[#142e25] p-4"><div><div className="flex items-center gap-2 text-sm font-bold"><Settings2 size={15} className="text-[#d6a944]" /> Maintenance mode</div><p className="mt-1 text-[11px] text-[#789385]">Pause new cash entries while open games finish.</p></div><button onClick={() => setMaintenance(!maintenance)} className={`relative h-7 w-12 rounded-full transition ${maintenance ? 'bg-[#d6a944]' : 'bg-[#355447]'}`} aria-label="Toggle maintenance mode"><span className={`absolute top-1 h-5 w-5 rounded-full bg-[#f2e9d1] transition ${maintenance ? 'left-6' : 'left-1'}`} /></button></div></div></section>
      <section className="panel-soft rounded-2xl p-6"><div className="mb-5 flex items-center gap-2"><Users size={18} className="text-[#d6a944]" /><h2 className="font-display text-xl font-bold">Live operations</h2></div><div className="space-y-3"><div className="flex items-center justify-between border-b border-[#345346] pb-3 text-xs"><span className="text-[#9cb2a2]">Completed matches</span><strong>642</strong></div><div className="flex items-center justify-between border-b border-[#345346] pb-3 text-xs"><span className="text-[#9cb2a2]">Pending deposits</span><strong className="text-[#f0d37c]">7</strong></div><div className="flex items-center justify-between border-b border-[#345346] pb-3 text-xs"><span className="text-[#9cb2a2]">Pending withdrawals</span><strong className="text-[#e49b8c]">3</strong></div><div className="flex items-center justify-between text-xs"><span className="text-[#9cb2a2]">Fair-play flags</span><strong className="text-[#67d895]">0 open</strong></div></div><button onClick={() => window.alert('Export is available once the server ledger is connected.')} className="btn-quiet mt-6 flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold"><Download size={14} /> Export report</button></section>
    </div>
    <section className="panel mt-5 rounded-2xl p-6"><div className="mb-5 flex items-center gap-2"><DollarSign size={18} className="text-[#d6a944]" /><h2 className="font-display text-xl font-bold">Recent settlement review</h2></div><div className="grid gap-3 md:grid-cols-3">{[['Kilimani Knockout', 'Entry KSh 200', 'Prize KSh 380', 'Fee KSh 20'], ['Ngong Road Blitz', 'Entry KSh 100', 'Prize KSh 190', 'Fee KSh 10'], ['Free table', 'No cash stake', 'No payout', 'No fee']].map(([name, entry, prize, feeText]) => <div key={name} className="rounded-xl border border-[#345346] bg-[#142e25] p-4"><div className="mb-3 flex items-center justify-between text-sm font-bold"><span>{name}</span><Check size={15} className="text-[#67d895]" /></div><div className="space-y-1 text-[11px] text-[#819a8d]"><div className="flex justify-between"><span>{entry}</span><span>{feeText}</span></div><div className="flex justify-between text-[#f0d37c]"><span>Winner receives</span><strong>{prize}</strong></div></div></div>)}</div></section>
  </div>;
}