/**
 * Home page — match highlight, daily fortune, career run and recent matches.
 * Extracted from App.tsx with identical testids and props.
 */
import { useState, type ReactNode } from 'react';
import { Link } from 'wouter';
import {
  ArrowRight, Check, ChevronRight, Coins, Dices, Flag, Play, Sparkles,
  Swords, Target, Zap,
} from 'lucide-react';
import { money, secureInt, type Mode } from '@/components/shell';
import { titleFor, type Career } from '@/components/game/player-store';
import { missions } from '@/features/stats';

function WalletChip({ mode, cashBalance = 2450 }: { mode: Mode; cashBalance?: number }) {
  return <div className={`flex items-center gap-2 rounded-full border px-3 py-2 text-xs font-semibold ${mode === 'cash' ? 'border-[#27875b]/50 bg-[#1c5f43]/20 text-[#62d694]' : 'border-[#d6a944]/40 bg-[#8a6b25]/15 text-[#e6c673]'}`}><Coins size={14} /> {mode === 'cash' ? 'Cash wallet' : 'Demo wallet'} <span className="font-mono-custom">{mode === 'cash' ? money(cashBalance) : 'KSh 8,750'}</span></div>;
}

export function HomePage({ mode, showToast, cashBalance, career }: { mode: Mode; showToast: (message: string) => void; cashBalance: number; career: Career }) {
  const [spinning, setSpinning] = useState(false);
  const [fortune, setFortune] = useState('Spin for tonight’s signal');
  const title = titleFor(career.xp);
  const outcomes = ['+120 XP', 'KSh 45 bonus', '2× entry shield', 'Good omen'];
  const spin = () => { if (spinning) return; setSpinning(true); setFortune('Reading the room…'); window.setTimeout(() => { setFortune(outcomes[secureInt(outcomes.length)]); setSpinning(false); showToast('Fortune locked in for tonight.'); }, 1800); };
  const totalGames = career.wins + career.losses;
  const winRate = totalGames ? Math.round((career.wins / totalGames) * 100) : 0;
  return <div className="reveal">
     <div className="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.22em] text-[#d6a944]"><span className="h-1.5 w-1.5 rounded-full bg-[#4fd28a]" /> Open source · free-first checkers</div><h1 className="font-display text-4xl font-bold leading-[.98] tracking-tight text-[#f2e9d1] sm:text-6xl">The board is<br /><span className="text-[#d6a944]">calling.</span></h1><p className="mt-4 max-w-md text-sm leading-relaxed text-[#829a8d]">Sharp moves, warm stakes. Play the bot, a partner, or the cash ladder — all under one neon Nairobi night.</p></div><div className="flex items-center gap-3"><WalletChip mode={mode} cashBalance={cashBalance} /><Link href="/play" data-testid="link-quick-play" className="btn-primary flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold"><Play size={16} fill="currentColor" /> Find a game</Link></div></div>
    <div className="grid gap-4 lg:grid-cols-[1.45fr_.8fr_.8fr]">
      <section className="glass-panel relative min-h-[260px] overflow-hidden rounded-2xl p-6 sm:p-8"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border border-[#d6a944]/15" /><div className="absolute -right-3 top-4 h-48 w-48 rounded-full border border-[#d6a944]/10" /><div className="relative z-10 flex h-full flex-col justify-between"><div><div className="mb-4 flex items-center gap-2 text-[10px] uppercase tracking-[.22em] text-[#809a8c]"><Zap size={14} className="text-[#d6a944]" /> Match highlight</div><h2 className="max-w-sm font-display text-2xl font-bold leading-tight">Three ways to play.<br /><span className="text-[#e0b957]">One neon board.</span></h2><p className="mt-3 max-w-xs text-xs leading-relaxed text-[#809a8c]">House bot at three temperaments, pass &amp; play with a partner, or the cash ladder with a transparent house fee.</p></div><Link href="/play" data-testid="link-rematch" className="mt-8 flex w-fit items-center gap-2 text-sm font-bold text-[#d6a944]">Pick your table <ArrowRight size={16} /></Link></div><div className="absolute bottom-7 right-8 hidden h-24 w-24 rotate-12 sm:block"><div className="grid h-full grid-cols-4 overflow-hidden rounded-lg border-2 border-[#d6a944]/40 bg-[#76522e] shadow-xl">{Array.from({ length: 16 }).map((_, index) => <div key={index} className={index % 2 === Math.floor(index / 4) % 2 ? 'bg-[#d6a944]/25' : 'bg-[#3b2921]/80'} />)}</div></div></section>
      <section className="glass-panel rounded-2xl p-5"><div className="flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-[.2em] text-[#829a8d]">Daily fortune</div><h2 className="mt-2 font-display text-xl font-bold">Tonight’s signal</h2></div><Sparkles size={17} className="text-[#d6a944]" /></div><div className={`mx-auto my-5 grid h-28 w-28 place-items-center rounded-full border-4 border-[#d6a944]/50 bg-[conic-gradient(#d6a944_0_20%,#254c3d_20%_40%,#d6a944_40%_60%,#254c3d_60%_80%,#d6a944_80%)] p-3 ${spinning ? 'wheel-spin' : ''}`}><div className="grid h-full w-full place-items-center rounded-full bg-[#18372e] text-center"><Dices size={19} className="text-[#d6a944]" /><span className="font-mono-custom text-[9px] text-[#cad8ca]">G2 / 254</span></div></div><p className="min-h-5 text-center text-xs text-[#d6a944]" data-testid="text-fortune-result">{fortune}</p><button onClick={spin} disabled={spinning} data-testid="button-spin-fortune" className="btn-quiet mt-4 w-full rounded-lg py-2.5 text-xs font-bold disabled:opacity-60">{spinning ? 'Spinning…' : 'Spin the wheel'}</button></section>
      <section className="glass-panel rounded-2xl p-5"><div className="flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-[.2em] text-[#829a8d]">Your run</div><h2 className="mt-2 font-display text-xl font-bold">{title.name}</h2></div><div className="grid h-9 w-9 place-items-center rounded-full bg-[#d6a944] font-display text-sm font-bold text-[#163229]">G2</div></div><div className="mt-6 flex items-end justify-between"><div><div className="font-display text-3xl font-bold">{career.xp.toLocaleString('en-KE')}</div><div className="text-[11px] text-[#829a8d]">XP {title.next ? `to ${title.next.name}` : '— summit reached'}</div></div><div className="text-right"><div className="text-xl font-bold text-[#60d692]">{winRate}%</div><div className="text-[11px] text-[#829a8d]">win rate</div></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#244438]"><div className="h-full rounded-full bg-[#d6a944]" style={{ width: `${title.next ? Math.min(100, Math.round(((career.xp - title.floor) / Math.max(1, title.ceiling - title.floor)) * 100)) : 100}%` }} /></div><Link href="/profile" data-testid="link-view-profile" className="mt-5 flex items-center justify-between text-xs font-bold text-[#d6a944]">View career <ChevronRight size={15} /></Link></section>
    </div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-xl font-bold">Recent matches</h2><Link href="/play" data-testid="link-see-all-games" className="text-xs font-bold text-[#d6a944]">Play now <ArrowRight className="ml-1 inline" size={13} /></Link></div><div className="space-y-2">{career.matches.slice(0, 3).map((match) => <ActivityRow key={match.id} title={`${match.outcome === 'win' ? 'Won' : 'Lost'} vs ${match.opponent}`} sub={`${new Date(match.at).toLocaleString('en-KE', { dateStyle: 'medium', timeStyle: 'short' })} · ${match.kind === 'bot' ? 'House AI' : match.kind === 'partner' ? 'Partner' : 'Cash ladder'}`} result={match.cashDelta > 0 ? `+ KSh ${match.cashDelta.toLocaleString('en-KE')}` : `+${match.xpDelta} XP`} icon={match.outcome === 'win' ? <Swords size={16} /> : <Flag size={16} />} positive={match.outcome === 'win'} />)}{career.matches.length === 0 && <div className="glass-panel-soft rounded-xl p-6 text-center text-xs text-[#7f9789]">No matches yet — your history will live here. Free play needs no account.</div>}</div></section><section className="glass-panel-soft rounded-2xl p-5"><div className="mb-4 flex items-center gap-2"><Target size={17} className="text-[#d6a944]" /><h2 className="font-display text-lg font-bold">Tonight’s missions</h2></div>{missions(career).map((mission) => <Mission key={mission.id} title={mission.label} progress={mission.progress} done={mission.done} />)}</section></div>
  </div>;
}

function ActivityRow({ title, sub, result, icon, positive }: { title: string; sub: string; result: string; icon: ReactNode; positive?: boolean }) {
  return <div className="glass-panel-soft flex items-center gap-3 rounded-xl px-4 py-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#23483a] text-[#d6a944]">{icon}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{title}</div><div className="text-[11px] text-[#789385]">{sub}</div></div><div className={`font-mono-custom text-xs ${positive ? 'text-[#63d492]' : 'text-[#b8c5b9]'}`}>{result}</div><ChevronRight size={15} className="text-[#607d6e]" /></div>;
}
function Mission({ title, progress, done }: { title: string; progress: string; done: boolean }) {
  return <div className="flex items-center gap-3 border-t border-[#345346] py-3 first:border-0 first:pt-0"><div className={`grid h-6 w-6 place-items-center rounded-full border ${done ? 'border-[#54c987] bg-[#23583f] text-[#69db9a]' : 'border-[#567568] text-transparent'}`}><Check size={13} /></div><div className="flex-1 text-xs font-semibold">{title}</div><span className={`font-mono-custom text-[10px] ${done ? 'text-[#69db9a]' : 'text-[#819a8d]'}`}>{progress}</span></div>;
}

